In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

documents = [
    "I love machine learning",
    "I love deep learning",
    "Machine learning is interesting"
]

# Step 1: Convert documents into a Count matrix
vectorizer = CountVectorizer()
count_matrix = vectorizer.fit_transform(documents)

print("Vocabulary:")
print(vectorizer.get_feature_names_out())

print("\nCount Matrix:")
print(count_matrix.toarray())

# Step 2: Calculate TF
tf = count_matrix.toarray() / count_matrix.toarray().sum(axis=1, keepdims=True)

print("\nTF Matrix:")
print(tf)

# Step 3: Calculate IDF
N = len(documents)
document_frequency = np.count_nonzero(count_matrix.toarray(), axis=0)

idf = np.log((N + 1) / (document_frequency + 1)) + 1

print("\nIDF:")
print(idf)

# Step 4: Calculate TF-IDF
tfidf = tf * idf

print("\nTF-IDF Matrix:")
print(tfidf)


Vocabulary:
['deep' 'interesting' 'is' 'learning' 'love' 'machine']

Count Matrix:
[[0 0 0 1 1 1]
 [1 0 0 1 1 0]
 [0 1 1 1 0 1]]

TF Matrix:
[[0.         0.         0.         0.33333333 0.33333333 0.33333333]
 [0.33333333 0.         0.         0.33333333 0.33333333 0.        ]
 [0.         0.25       0.25       0.25       0.         0.25      ]]

IDF:
[1.69314718 1.69314718 1.69314718 1.         1.28768207 1.28768207]

TF-IDF Matrix:
[[0.         0.         0.         0.33333333 0.42922736 0.42922736]
 [0.56438239 0.         0.         0.33333333 0.42922736 0.        ]
 [0.         0.4232868  0.4232868  0.25       0.         0.32192052]]
