In [4]:
# ============================================================
# NLP LAB - INSTALLATION CELL
# ============================================================

!pip install -q gensim pyemd scikit-learn textblob vaderSentiment
!pip install -q spacy
!python -m spacy download en_core_web_sm

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 4.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 94.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [12]:
# ============================================================
# PROGRAM 22
# SEQUENCE CLASSIFICATION USING LSTM
# ============================================================

import numpy as np

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Embedding,
    LSTM,
    Dense
)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# ------------------------------------------------------------
# STEP 1: Dataset
# ------------------------------------------------------------

texts = [
    "I love this movie",
    "This movie is amazing",
    "The movie was excellent",
    "I really enjoyed the film",
    "This is a wonderful movie",

    "I hate this movie",
    "This movie is terrible",
    "The movie was boring",
    "I disliked the film",
    "This movie is horrible"
]

# 1 = Positive
# 0 = Negative

labels = np.array([
    1, 1, 1, 1, 1,
    0, 0, 0, 0, 0
])

# ------------------------------------------------------------
# STEP 2: Tokenization
# ------------------------------------------------------------

vocab_size = 1000

tokenizer = Tokenizer(
    num_words=vocab_size,
    oov_token="<OOV>"
)

tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)

# ------------------------------------------------------------
# STEP 3: Padding
# ------------------------------------------------------------

max_length = 6

X = pad_sequences(
    sequences,
    maxlen=max_length,
    padding="post"
)

print("Padded Input:")
print(X)

# ------------------------------------------------------------
# STEP 4: Build LSTM Model
# ------------------------------------------------------------

model = Sequential([

    Embedding(
        input_dim=vocab_size,
        output_dim=32
    ),

    LSTM(32),

    Dense(
        1,
        activation="sigmoid"
    )
])

# ------------------------------------------------------------
# STEP 5: Compile
# ------------------------------------------------------------

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# ------------------------------------------------------------
# STEP 6: Display Model
# ------------------------------------------------------------

model.summary()

# ------------------------------------------------------------
# STEP 7: Train
# ------------------------------------------------------------

model.fit(
    X,
    labels,
    epochs=20,
    verbose=1
)

# ------------------------------------------------------------
# STEP 8: Test New Sentence
# ------------------------------------------------------------

test_sentence = [
    "this movie is amazing"
]

test_sequence = tokenizer.texts_to_sequences(
    test_sentence
)

test_padded = pad_sequences(
    test_sequence,
    maxlen=max_length,
    padding="post"
)

prediction = model.predict(
    test_padded,
    verbose=0
)

probability = prediction[0][0]

print("\n================================")
print("PREDICTION")
print("================================")

print("Probability:", probability)

if probability >= 0.5:
    print("Sentiment: POSITIVE")
else:
    print("Sentiment: NEGATIVE")

Padded Input:
[[ 4  9  3  2  0  0]
 [ 3  2  5 10  0  0]
 [ 6  2  7 11  0  0]
 [ 4 12 13  6  8  0]
 [ 3  5 14 15  2  0]
 [ 4 16  3  2  0  0]
 [ 3  2  5 17  0  0]
 [ 6  2  7 18  0  0]
 [ 4 19  6  8  0  0]
 [ 3  2  5 20  0  0]]


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 3s 3s/step - accuracy: 0.3000 - loss: 0.6935
Epoch 2/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6000 - loss: 0.6929
Epoch 3/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.6000 - loss: 0.6924
Epoch 4/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6000 - loss: 0.6919
Epoch 5/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.8000 - loss: 0.6913
Epoch 6/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.9000 - loss: 0.6907
Epoch 7/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - accuracy: 0.9000 - loss: 0.6901
Epoch 8/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9000 - loss: 0.6895
Epoch 9/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - accuracy: 0.9000 - loss: 0.6888
Epoch 10/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9000 - loss: 0.6881
Epoch 11/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.9000 - loss: 0.6874
Epoch 12/20
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.9000 - loss: 0.6866
Epo